### ISSUE TITLE
It's all yours

### ISSUE THREAD

**Issue by shawnthompson** [shawnthompson/GCWeb-search#1]
@neoinsight, I created this repo for you to work with. It's using the latest GCWeb files.

Here's the gh-pages site: http://shawnthompson.github.io/GCWeb-search/index-en.html

Let me know if you need help. Please share it.

cc/ @pcwsmith

PS I think we should move the H1 above both columns, below the search field.

![image](https://cloud.githubusercontent.com/assets/2575266/13265338/6a8cca64-da40-11e5-970d-c5906f9b4550.png)

PSS I lost connection to my ESDC network and email :-1:

**Comment by neoinsight** [comment]
Thanks!!  Am already messing around with it! Agree re heading.

**Comment by shawnthompson** [comment]
@neoinsight Can we make this suggestion about the moving the heading? I would also like to suggest putting a heading on the right side.

I like headings :)

**Comment by pcwsmith** [comment]
thumbs up on the main header idea from over here.

not sure what you mean about a header on the right - ie the main column that lists the results?

**Comment by shawnthompson** [comment]
Like this:

![image](https://cloud.githubusercontent.com/assets/2575266/13321946/1901a3fc-dba0-11e5-9b8d-70e0547a516e.png)

@pcwsmith can you tell I like headings? You just got another email from me about another heading :+1:

**Comment by neoinsight** [comment]
@shawnthompson Can you fix the heading(s) for me please in this repo? I'm not sure how to do that.

**Comment by shawnthompson** [comment]
@neoinsight @pcwsmith, are we putting a new heading on the right side? If so, what do I put?

**Comment by neoinsight** [comment]
@shawnthompson Urg, never like to add a heading that we don't really really need. And if we right away don't know what to call it, that's a clue. Hmm. Are you SURE we need a heading there? I am not keen. Even the one moved above. Let's try without first please?

**Comment by shawnthompson** [comment]
If you look at the document heading structure it now looks weird.

![image](https://cloud.githubusercontent.com/assets/2575266/13324150/7533b5f2-dbaa-11e5-82ff-942ccf1ee3cb.png)

Filter by is at the same level as all the links to the results.

**Comment by neoinsight** [comment]
Ah, where would the new 'Results' heading go? Could it be invisible - e.g. visible only to screenreaders?

**Comment by neoinsight** [comment]
How do you do that cool thing of seeing the headings like that?

**Comment by shawnthompson** [comment]
it's a plugin for chrome and FF

http://chrispederick.com/work/web-developer/

View Document Outline

![image](https://cloud.githubusercontent.com/assets/2575266/13324331/34094dde-dbab-11e5-9439-507dfb4e6109.png)

**Comment by shawnthompson** [comment]
I'm not big on hidden headings anymore, we discussed the breadcrumbs issue in my gh-pages demo:

I sent this to a colleague today:

> Breadcrumbs for example:
 
``` HTML
<nav property="breadcrumb" id="wb-bc" role="navigation"><h2 class="wb-inv">You are here:</h2>
<div class="container"><div class="row">
<ol class="breadcrumb">
<li><a href="/en.html">Home</a></li>
</ol></div></div></nav>

```
> Are you really there? No, because the page title has been removed from the breadcrumb path so this hidden heading now does not make sense…

**Comment by shawnthompson** [comment]
out of sight out of mine :-1:

**Comment by neoinsight** [comment]
Ok. Thanks  Hmm, what I'm trying to do is not push the results down the page too far on mobile, while still meeting the needs of screenreaders. Both mobile and screenreaders use search a lot. What else can we do to meet that goal?

**Comment by shawnthompson** [comment]
Do mobile users not like to scroll?

I added the other heading back and did another document outline:

![image](https://cloud.githubusercontent.com/assets/2575266/13324876/7b513952-dbad-11e5-80a3-74515c9ccd88.png)

I like that better personally.

**Comment by neoinsight** [comment]
Well no, mobile users don't like to scroll to see their main task - other stuff yes they are willing, but for search etc, they want to see the first results when the page loads. 
That structure looks good. But when the results aren't filtered (e.g. set to 'all'), can't call it that. Also lets make sure the number of results is to the left of the filters (like on Gov.Uk publications search), not above, so that it is within the filtered headings set, rather than above. Oh hey, this is the answer!! Look what they did: the number of results is the heading on the left! How about that?
![image](https://cloud.githubusercontent.com/assets/1855584/13325106/74b8e92c-dbae-11e5-8d48-67baaae6ec1c.png)

**Comment by shawnthompson** [comment]
BTW here's what gov.uk's document structure is like:
![image](https://cloud.githubusercontent.com/assets/2575266/13325336/63c0fe10-dbaf-11e5-8aed-9cf55be2a00f.png)

Not very good, I'll work on a sample of ours with your suggestions

**Comment by shawnthompson** [comment]
![image](https://cloud.githubusercontent.com/assets/2575266/13325457/f4763aec-dbaf-11e5-957b-6ab68298ddd0.png)

![image](https://cloud.githubusercontent.com/assets/2575266/13325480/1138260e-dbb0-11e5-8453-9b68987a2f25.png)

TEAM WORK!!!

That's much better, do we still want the "about word in there"

**Comment by neoinsight** [comment]
Excellent!! Lovely, let's go with that. No, skip the 'About' 
I want to change the numbers anyway - while you are editing, if you get a chance, put the 99,000 on the 'all-results-en' page, then '99' on the index-en for filtered to Service Canada and '9' for the hc-results-en for filtered to health canada.  Partiicpants really noticed and used those numbers in the previous testing, need to get them rightish so it doesn't confuse them. Thanks - gotta go.

**Comment by shawnthompson** [comment]
Done! and created a landing page to list the pages.

http://shawnthompson.github.io/GCWeb-search/index.html

**Comment by pcwsmith** [comment]
Nb The about was there b/c the numbers of results that the system returns are approximate. In fact, they change kinda randomly between one search and the next. 

Just did two searches on "passport" in two separate tabs open to canada.ca. One gave me 18,500, the other gave me 18,400.

**Comment by shawnthompson** [comment]
What if we put (approximately) at the end in a `small`?

**Comment by shawnthompson** [comment]
![image](https://cloud.githubusercontent.com/assets/2575266/13328118/f6a9d2aa-dbba-11e5-867b-62fd30a924c4.png)

**Comment by pcwsmith** [comment]
Prefer keeping the About in there. It' what google.ca does, actually.

**Comment by shawnthompson** [comment]
Done sir!

http://shawnthompson.github.io/GCWeb-search/index.html

**Comment by neoinsight** [comment]
Ok, I have made one more change - just to try in the usability testing - and that is that if you click on the 'Selected organization' above the details/summary, it will clear it (as if it really was a facet and you unclicked the checkbox'. Just wanted it to be in place in case someone tries this, we will watch during the testing to see if anyone ever does...

**Comment by neoinsight** [comment]
This is working well in the testing so far -closing this issue - thank you all!
