### ISSUE TITLE
How add employment into search field?

### ISSUE THREAD

**Issue by neoinsight** [shawnthompson/GCWeb-search#2]
@shawnthompson Can you advise on how to make 'employment' show up in the search field? That's the way the real search works. Thanks!

Also, I couldn't make the check mark icon show up IN the list in the details summary, not sure why. But for example, on index-en, I was hoping that Service Canada (at the bottom of the Most Requested list) would have a check mark. 

None of those are killer issues. 

BTW, we think there is a caching problem on the gh pages - some of my updates are just NOT showing up in the pages, even though the code on this repo clearly shows the changes. For example, on line 148 of hc-results-en,  'Service Canada' is linked to the index page (index-en), but on the page, despite many reloads, it still shows the old link to the actual servicecanada.gc. site - more than 12 hours since the change. 
@steve-h says we can possibly redirect or something. Just asking in case you've seen this in the past.

**Comment by shawnthompson** [comment]
@neoinsight, if you add ` placeholder="Search term"` in the input field. I thought they were using that on the real search but they are using the `value` attribute which you shouldn't use in this case. I'll speak to Cristian about changing it to the `placeholder` instead.

Here's the HTML for the Service Canada link with the checkmark in the list
``` html
<li><a href="http://shawnthompson.github.io/GCWeb-search/index-en.html">Service Canada</a> <i class="glyphicon glyphicon-ok"></i></li>
```

![image](https://cloud.githubusercontent.com/assets/2575266/13321167/6b7daf7c-db9b-11e5-93f9-f54c3e867a38.png)


The Service Canada link in the left is set to `http://shawnthompson.github.io/GCWeb-search/index-en.html`. You might need to hard refresh your browser window, not sure.

**Comment by shawnthompson** [comment]
@neoinsight so we will use `value` not `placeholder`... gotcha!

**Comment by shawnthompson** [comment]
I will fix it with the heading change :+1:
