### ISSUE TITLE
Mobile view messed up

### ISSUE THREAD

**Issue by neoinsight** [shawnthompson/GCWeb-search#4]
@shawnthompson the mobile participants today had a hard time with this search prototype. The view is messed up - some of the results are wide and it's making the whole rest of the view narrow on their phone. 

Oddly enough, I was just about to post an issue on WET about how it's too easy for this to happen. I had emailed someone else today to tell them to fix the same problem - they had a photo on a page and it had caused this same problem. And have sent similar messages in the past. 

![narrow search](https://cloud.githubusercontent.com/assets/1855584/13442493/77cc652e-dfca-11e5-80ec-4238102d111f.png)

**Comment by shawnthompson** [comment]
It's the long URLs on the pages

**Comment by neoinsight** [comment]
But what can we do?

**Comment by shawnthompson** [comment]
Why are they there? Screen reader users have to love those. It's good that they aren't linked but stuff annoying to be read. 

Shawn Thompson 
Plansmash@me.com

**Comment by neoinsight** [comment]
Those are real search results, pasted from a real search results page aren't they? I thought we started from your demo... For the health results that I added, I pasted them in from the live search.

**Comment by neoinsight** [comment]
The live site is broken that way!! Just tested same search term on my phone and get the tiny view. Gah. 

![search on mobile](https://cloud.githubusercontent.com/assets/1855584/13443696/3902ba0e-dfd0-11e5-97f2-a4146cf604cd.png)

**Comment by neoinsight** [comment]
I will hand edit the offending long links in our prototype to shorten them, although they then won't work - but it's not part of the task to click on a link anyway. Am hoping you or someone there can deal with the issue on the live site.

**Comment by neoinsight** [comment]
@shawnthompson @pcwsmith This issue of squished search pages happened in other searches the mobile participants performed. Don't want it to get lost - it's impacting visitors on the site daily...
![search squished in mobile](https://cloud.githubusercontent.com/assets/1855584/13957281/47624440-f022-11e5-8fa4-01e227223c7d.png)

**Comment by shawnthompson** [comment]
What did we decide to do about the long URLs? Are we going to do the ellipsis... ? Maybe I could create a utility class in WET to apply to all those URLs.

**Comment by neoinsight** [comment]
Better discussion here - I should have closed that one and moved it to here. Will do so now. 
But yes, ellipses so URL fits in a single line of text. 
 https://github.com/wet-boew/GCWeb/issues/1079

**Comment by shawnthompson** [comment]
Actually maybe we should keep the other discussion going on GCWeb. This repository is just setup for a demo and will be deleted once it's done.

**Comment by neoinsight** [comment]
Closing this discussion - see wet-boew/GCWeb#1079
